// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdodsqEAb_TCQJXWA3Q0HDhCxJ6rRQRU0',
    appId: '1:601094163822:web:8dc2848028d42e010a857f',
    messagingSenderId: '601094163822',
    projectId: 'uniserve-fa0a3',
    authDomain: 'uniserve-fa0a3.firebaseapp.com',
    storageBucket: 'uniserve-fa0a3.firebasestorage.app',
    measurementId: 'G-BT2BHBBRDY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA10SfQEVM5iA8Po8Ri0lEvcsDIUGFYEdM',
    appId: '1:601094163822:android:e0a33bde281f30400a857f',
    messagingSenderId: '601094163822',
    projectId: 'uniserve-fa0a3',
    storageBucket: 'uniserve-fa0a3.firebasestorage.app',
  );
}
